# Generated by Django 5.1.4 on 2024-12-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('advance', 'In advance'), ('on_pickup', 'On pickup')], default='on_pickup', max_length=20),
        ),
    ]
